sonar.projectKey=aiconnectionmanager
sonar.projectName=AIGateway secure WebSocket service
sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.exclusions=.git/**,.github/**,.tools/**,configs/**,**/*.pem,**/*.crt,**/*.key,coverage.out
sonar.go.coverage.reportPaths=coverage.out
sonar.sourceEncoding=UTF-8
